### ISSUE TITLE
Assimp build error with gcc-14

### ISSUE THREAD

**Issue by theartful** [facebookresearch/ocean#12]
## Instructions to reproduce the problem:

When building the third party libraries I get the error
```
In member function ‘bool aiString::operator==(const aiString&) const’,
    inlined from ‘void Assimp::ObjFileParser::getMaterialDesc()’ at /home/theartful/build_ocean_thirdparty/third-party_cache/assimp/33d84aa4f2c2ba4a1a48bea47ef7749ccc9b9941/code/AssetLib/Obj/ObjFileParser.cpp:587:80:
/home/theartful/build_ocean_thirdparty/third-party_cache/assimp/33d84aa4f2c2ba4a1a48bea47ef7749ccc9b9941/include/assimp/types.h:347:54: error: ‘<anonymous>’ may be used uninitialized [-Werror=maybe-uninitialized]
  347 |         return (length == other.length && 0 == memcmp(data, other.data, length));
      |                                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
<built-in>: In member function ‘void Assimp::ObjFileParser::getMaterialDesc()’:
<built-in>: note: by argument 2 of type ‘const void*’ to ‘int __builtin_memcmp_eq(const void*, const void*, long unsigned int)’ declared here
/home/theartful/build_ocean_thirdparty/third-party_cache/assimp/33d84aa4f2c2ba4a1a48bea47ef7749ccc9b9941/code/AssetLib/Obj/ObjFileParser.cpp:587:99: note: ‘<anonymous>’ declared here
  587 |     if (m_pModel->mCurrentMaterial && m_pModel->mCurrentMaterial->MaterialName == aiString(strName)) {
      |
```

## Expected behavior:

Should build as expected.

## Suggested solution:

The assimp developers fixed the issue in https://github.com/assimp/assimp/pull/5593, so we can either update assimp to 5.4.2, or we can pull their patch into `assimp.patch`, or maybe disable `Werror` for assimp (should be disabled for third party libraries in general imo).

**Comment by enpe** [comment]
Thanks for reporting this! And for suggesting a potential solution! We'll take a closer look at this.

**Comment by theartful** [comment]
@enpe I'm running archlinux, which is a hassle I know since it's a rolling release, and so I get these problems with newer versions of stuff. It's a compiler issue though with gcc-14.

**Comment by enpe** [comment]
@theartful, and did you confirm it builds fine again with assimp 5.4.2? You can test it here:

https://github.com/facebookresearch/ocean/blob/8c31cdaa859ad74dae5dee240a2d55679e91bfff/build/cmake/third-party/assimp.cmake#L35

**Comment by theartful** [comment]
@enpe Yep, I did. I applied this patch locally, and all dependencies built fine, and as far as I know the newer changes only introduces bug fixes, so it should not be breaking.

I'm still having other build problems, so I couldn't run the test suite.

**Comment by leapally** [comment]
I have repro'd the bug with gcc-14.

Options "-Wall" and "-Werror" are coming from assimp configuration:
https://github.com/assimp/assimp/blob/206839d4f23162fb515010d5d93a21e1bbde5c50/code/CMakeLists.txt#L1274

Haven't found Ocean config that adds these if they exist somewhere.  I guess we could override their config, but going to try 5.4.2 first to see if that works.

**Comment by leapally** [comment]
[This commit](https://github.com/facebookresearch/ocean/commit/c477d7153351e4106fb560f939035aba0c422e75) updates dependency on assimp to version v5.4.2.  Build succeeds on Linux (GCC 13/14, Clang), Windows (MSVC), and MacOS(Apple Clang).
