### ISSUE TITLE
How to align the coordinate systems of the external camera and the Quest's camera?

### ISSUE THREAD

**Issue by AplusX** [facebookresearch/ocean#14]
Thanks for providing the Ocean framework!

Since the Quest does not allow users to access built-in camera data, how can we align the coordinate systems of the external camera and Quest's camera?  

I didn't find any relevant information in the development documentation (https://facebookresearch.github.io/ocean/docs/introduction/)

**Comment by atom2-source** [comment]
There isn't a official calibration yet but seeing passthrough and the view from the external camera you can align them really close by eye there's alot of cv tools for rotation etc it's something you should only have to do once if the camera is secured and maybe check it every update.

**Comment by AplusX** [comment]
> There isn't a official calibration yet but seeing passthrough and the view from the external camera you can align them really close by eye there's alot of cv tools for rotation etc it's something you should only have to do once if the camera is secured and maybe check it every update.

That's true. But it is almost impossible to align them accurately just by the user's eyes. Note that to enable Quest passthrough mode, the extra camera needs to support ARM64 architecture. I am trying to align Realsense with Quest.

**Comment by atom2-source** [comment]
I'll be doing it weekend with my quest pro I figure close enough is good enough a few buttons for the cv image manipulation so you can control it while wearing would be my start and look at a target of some kind.it won't be super accurate but I figure if I can't see a difference a user of the application won't image segmentation might be a bit of a ask with eye alignment only a display that showed how much you have altered the image from the webcam would be another good place to start so you can do eye alignment write it down then you have a really good starting point for image correction.

**Comment by enpe** [comment]
This is a great suggestion. And, yes, it's already on our radar. Please bare in mind that the support for external USB cameras is still very new. So, not everything will be immediately available.

**Comment by AplusX** [comment]
> This is a great suggestion. And, yes, it's already on our radar. Please bare in mind that the support for external USB cameras is still very new. So, not everything will be immediately available.

May I know if Meta has a plan to release the access permission of Quest camera?

**Comment by A-Ivan** [comment]
I'm also curious about this. 

While there are ways to perform the calibration process ourselves, for instance using a planar calibration checkerboard ([tutorial 1](https://medium.com/@chaitalibh.cb/camera-calibration-with-checkerboard-54f93af742a0), [tutorial 2](https://github.com/hjoonpark/MultiCamCalib), [tutorial 3](https://www.youtube.com/watch?v=EWqqseIjVqM&ab_channel=LearnOpenCV), [tutorial 4](https://www.youtube.com/watch?v=Wcnb197g2i0&ab_channel=KevinWood%7CRobotics%26AI), [tutorial 5](https://github.com/cvlab-epfl/multiview_calib), [stereo camera calibration explanation](https://www.youtube.com/watch?v=hUVyDabn1Mg&ab_channel=FirstPrinciplesofComputerVision)), it would be easier if there were an official solution from Meta. Is there any update on an official calibration procedure?

Is there any update on when Meta will release access to onboard the camera (and depth sensor)?
