### ISSUE TITLE
A Photogrammetry example please?

### ISSUE THREAD

**Issue by Shubhra22** [facebookresearch/ocean#30]
Is it possible to get a photogrammetry sample project? Or at least some direction on how to get started?

**Comment by leapally** [comment]
Hi @Shubhra22.  Apologies for the late reply.

Maybe we can help you better if we knew what your goal is.
- Could you describe the photogrammetry task you are working on?
  - For example, you could describe what the input is and what the desired output is.
- What are you currently blocked on?
- What subset of functionalities would be most helpful if they were implemented in a sample project?

Thanks for your input!

**Comment by Shubhra22** [comment]
Hey @leapally It's my turn now to say sorry for the late reply.

1. Ideally, I am looking for the following workflow: User upload a set of images and gets out a textured mesh. If it's a too much of an ask, may be direct me what classes/ files I should look into to implement something myself. 

2. I am currently using open3d api for this, but there is not any direct mobile device support from it. I understand the whole process of a reconstruction from a higher level, (from using API like open3d), so its little overwhelming to find which particular classes I should look into/ use to create a 3d reconstruction. 

3. I would say if there was at least an example for Structure from Motion or may be a mesh reconstruction that might be very helpful.

**Comment by leapally** [comment]
Hey, @Shubhra22.  Thanks for the reply.

I see that there is a [Windows demo named "structurefrommotion"](https://github.com/facebookresearch/ocean/tree/main/impl/application/ocean/demo/tracking/offline/structurefrommotion/win)  available.  I'm not familiar with this particular demo, but I can ping the team tomorrow about it and see whether a structure from motion demo on mobile platforms is something that is doable.

**Comment by leapally** [comment]
Hey, @Shubhra22.

Conclusion from discussion was that we don't have bandwidth to create photogrammetry demos for mobile platforms at the moment.  I'll see if I can find examples within existing code that might help aside from "structurefrommotion".

**Comment by Shubhra22** [comment]
Thanks @leapally, I will look into the windows demo to start with.
