### ISSUE TITLE
SLAM examples

### ISSUE THREAD

**Issue by julapy** [facebookresearch/ocean#38]
It would be great to see a SLAM example.
more specifically, showing a spare map being created in real-time with on-device localization.
is this possible?

Photogrammetry is also mentioned in the list of features on the homepage but its not immediately clear how to piece together the code to achieve this. An example would be immensely helpful for developers.

**Comment by leapally** [comment]
Hi @julapy, thank you for the suggestion.

Like with the request for photogrammetry example, the team currently does not have bandwidth for this type of enhancement.

But this seems like a useful addition and we'll keep track of it to work on when we can make time for this type of change.
