### ISSUE TITLE
Issue with Calibration Pattern Detection

### ISSUE THREAD

**Issue by ranjitkathiriya544** [facebookresearch/ocean#40]
I’ve been trying to use various calibration patterns (Aruco, checkerboard, dot patterns) for my calibration code, but none of them seem to work. Below is the code I’m using:

```
#include "ocean/base/Frame.h"
#include "ocean/io/image/Image.h"
#include "ocean/cv/FrameInterpolator.h"
#include "ocean/cv/detector/CalibrationPatternDetector.h"
#include "ocean/cv/FrameConverter.h"
#include "ocean/base/WorkerPool.h"

#include <iostream>

using namespace std;
using namespace Ocean;

const Frame loadedFrame = IO::Image::readImage("./images/image_2.png");

if (!loadedFrame.isValid()) {
    std::cerr << "Could not open or find the image!" << std::endl;
    return -1;
} else {
    cout << "Image successfully loaded!!!" << endl;
}

Worker* worker = nullptr;

const unsigned int rows = 2;
const unsigned int cols = 2;

cout << "rows : " << detector.horizontalBoxes() << endl;
cout << "Cols : " << detector.verticalBoxes() << endl;

bool result = detector.detectPattern(targetFrame, WorkerPool::get().scopedWorker()());

std::cout << detector.isValid() << endl;

// Check the result
if (result) {
    std::cout << "Pattern detected successfully. " << result << std::endl;
} else {
    std::cout << "Pattern detection failed. " << result << std::endl;
}

return 0;

```

No matter which calibration pattern I try, the result is always 0. Could someone help me identify what might be going wrong?

**Comment by thorntondr** [comment]
From the [documentation](https://facebookresearch.github.io/ocean/doxygen/class_ocean_1_1_c_v_1_1_detector_1_1_calibration_pattern_detector.html#details)

> The calibration pattern is composed by a rectangular grid of black quadratic boxes.
All boxes must have the same size the white space between the boxes must match the box size.

Here is a picture of an example
![WIN_20240319_09_15_02_Pro](https://github.com/user-attachments/assets/81e43073-2fa8-4ea7-82f3-f89764635fd5)

**Comment by thorntondr** [comment]
Added a calibration pattern generator demo app in commit 2585082716247926bdd7f53e0437d04f1740d941. Hope this helps.

**Comment by ranjitkathiriya544** [comment]
Thanks!
