### ISSUE TITLE
Planar RGB Formats

### ISSUE THREAD

**Issue by robo-todd** [facebookresearch/ocean#42]
## 🚀 Feature

Add planar RGB formats (like those required by nearly all vision-based neural networks) to the list of supported formats and add conversion functions for this very common use-case.

Conceptually this would be adding a FORMAT_R_G_B24 and a FORMAT_B_G_R24 (and perhaps others) to the FrameType PixelFormat enumeration where there are 3 planes of 8 bit size and so forth. These could be added after all the YUV planar formats. Basically FORMAT_Y_U_V24 but with R,G and B planes.

## Motivation & Examples

Ocean gives us an opportunity to avoid dependencies on OpenCV in our mixed classical/neural vision code, but we end up doing a bunch of extra 'manual' conversions because there is no support for the planar RGB formats (Plane of R, plane of G, plane of B) format and associated conversion code.

Would you be able/willing to contribute to this work? Yes.

**Comment by thorntondr** [comment]
Thanks for the request. We'll look into adding this.

**Comment by thorntondr** [comment]
Can you give us an idea of which predefined conversions will be most helpful (i.e. convertR_G_B24ToRGB24)?

**Comment by robo-todd** [comment]
Checked with our developer team internally.  We really just need R_G_B24 as a target format because so many networks take that as their input format (YOLO family, etc.). We would want at least:  RGB24 to R_G_B24 as a conversion and then the reverse that you list above. I think it would get a lot of use as people start integrating Ocean /w AI components. Thanks!

**Comment by thorntondr** [comment]
Completed w/ commit 6d56c14416366971368b1d466aa084e5e769c77c
